# Generated by Django 4.2.4 on 2024-02-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='myData',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataId', to='Data_Privacy_Vault.id')),
            ],
        ),
    ]
